'------------------------------------------------------------------------------
' <auto-generated>
'     This code was generated from a template.
'
'     Manual changes to this file may cause unexpected behavior in your application.
'     Manual changes to this file will be overwritten if the code is regenerated.
' </auto-generated>
'------------------------------------------------------------------------------

Imports System
Imports System.Collections.Generic

Namespace Mvc_Angular_Crud

    Partial Public Class Produtos
        Public Property Id As Integer
        Public Property ProdutoNome As String
        Public Property ProdutoPreco As Nullable(Of Decimal)
    
    End Class

End Namespace
